version: "3.9"

services:
  rating-service:
    build:
      context: ./RatingService/RatingService
      dockerfile: Dockerfile
    container_name: rating-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - ConnectionStrings__DefaultConnection=Server=devops-sql,1433;Database=RatingServiceDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - Services__Accommodation__BaseUrl=http://accommodation-service:8080

      - RabbitMq__Host=rabbitmq
      - RabbitMq__User=guest
      - RabbitMq__Pass=guest
      - RabbitMq__VirtualHost=/
      - RabbitMq__Exchange=integration
    networks:
      - shared-net
    ports:
      - "5003:8080"

networks:
  shared-net:
    external: true
    name: shared-net
